------------------------------------------
--PART CATALOG DATA-----------------
------------------------------------------
--FOR PART_CATALOG data
CREATE OR REPLACE FORCE VIEW "IFSAPP"."SCG_COPY_PART_CATALOG" (
-- PART_CATALOG_TAB columns:
    "PART_NO_PC", "DESCRIPTION", "PART_MAIN_GROUP", "INFO_TEXT", "STD_NAME_ID", "UNIT_CODE", "ROWVERSION_PC", "SERIAL_TRACKING_CODE", "ENG_SERIAL_TRACKING_CODE", "SERIAL_RULE",
    "LOT_TRACKING_CODE", "CONFIGURABLE", "CUST_WARRANTY_ID", "SUP_WARRANTY_ID", "CONDITION_CODE_USAGE", "LOT_QUANTITY_RULE", "SUB_LOT_RULE", "POSITION_PART",
    "INPUT_UNIT_MEAS_GROUP_ID", "CATCH_UNIT_CODE", "CATCH_UNIT_ENABLED", "MULTILEVEL_TRACKING", "COMPONENT_LOT_RULE", "TEXT_ID$", "STOP_ARRIVAL_ISSUED_SERIAL",
    "ALLOW_AS_NOT_CONSUMED", "WEIGHT_NET", "VOLUME_NET", "UOM_FOR_WEIGHT_NET", "UOM_FOR_VOLUME_NET", "FREIGHT_FACTOR", "RECEIPT_ISSUE_SERIAL_TRACK", "STOP_NEW_SERIAL_IN_RMA",
    "STORAGE_WIDTH_REQUIREMENT", "STORAGE_HEIGHT_REQUIREMENT", "STORAGE_DEPTH_REQUIREMENT", "UOM_FOR_LENGTH", "STORAGE_VOLUME_REQUIREMENT", "UOM_FOR_VOLUME", "STORAGE_WEIGHT_REQUIREMENT",
    "UOM_FOR_WEIGHT", "MIN_STORAGE_TEMPERATURE", "MAX_STORAGE_TEMPERATURE", "UOM_FOR_TEMPERATURE", "MIN_STORAGE_HUMIDITY", "CAPACITY_REQ_GROUP_ID", "CONDITION_REQ_GROUP_ID", "CAPABILITY_REQ_GROUP_ID", "ROWKEY_PC",
-- PART_CATALOG_cft custom field columns
    "CF$_PIM_FLAG"
    ) AS 
SELECT 
    pc.PART_NO, pc.DESCRIPTION, pc.PART_MAIN_GROUP, pc.INFO_TEXT, pc.STD_NAME_ID, pc.UNIT_CODE, pc.ROWVERSION, pc.SERIAL_TRACKING_CODE, pc.ENG_SERIAL_TRACKING_CODE, pc.SERIAL_RULE,
    pc.LOT_TRACKING_CODE, pc.CONFIGURABLE, pc.CUST_WARRANTY_ID, pc.SUP_WARRANTY_ID, pc.CONDITION_CODE_USAGE, pc.LOT_QUANTITY_RULE, pc.SUB_LOT_RULE, pc.POSITION_PART,
    pc.INPUT_UNIT_MEAS_GROUP_ID, pc.CATCH_UNIT_CODE, pc.CATCH_UNIT_ENABLED, pc.MULTILEVEL_TRACKING, pc.COMPONENT_LOT_RULE, pc.TEXT_ID$, pc.STOP_ARRIVAL_ISSUED_SERIAL,
    pc.ALLOW_AS_NOT_CONSUMED, pc.WEIGHT_NET, pc.VOLUME_NET, pc.UOM_FOR_WEIGHT_NET, pc.UOM_FOR_VOLUME_NET, pc.FREIGHT_FACTOR, pc.RECEIPT_ISSUE_SERIAL_TRACK, pc.STOP_NEW_SERIAL_IN_RMA,
    pc.STORAGE_WIDTH_REQUIREMENT, pc.STORAGE_HEIGHT_REQUIREMENT, pc.STORAGE_DEPTH_REQUIREMENT, pc.UOM_FOR_LENGTH, pc.STORAGE_VOLUME_REQUIREMENT, pc.UOM_FOR_VOLUME, pc.STORAGE_WEIGHT_REQUIREMENT,
    pc.UOM_FOR_WEIGHT, pc.MIN_STORAGE_TEMPERATURE, pc.MAX_STORAGE_TEMPERATURE, pc.UOM_FOR_TEMPERATURE, pc.MIN_STORAGE_HUMIDITY, pc.CAPACITY_REQ_GROUP_ID, pc.CONDITION_REQ_GROUP_ID, pc.CAPABILITY_REQ_GROUP_ID, pc.ROWKEY,
    pccft.CF$_PIM_FLAG
FROM ifsapp.PART_CATALOG_cft pccft, ifsapp.PART_MANUFACTURER_TAB pm, ifsapp.PART_MANU_PART_NO_TAB pmp, ifsapp.PART_CATALOG_TAB pc
WHERE 1=1
  AND pc.ROWKEY = pccft.ROWKEY
  AND pc.PART_NO = pm.PART_NO
  AND pmp.PART_NO = pc.PART_NO
  AND pm.MANUFACTURER_NO = pmp.MANUFACTURER_NO
  AND pc.PART_NO = '5308509'
  AND pm.MANUFACTURER_NO = 'BR-SP'
  AND (
        to_number(to_char(pc.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600) -- record was changed in the last 60 mins
      OR
        to_number(to_char(pm.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      OR
        to_number(to_char(pmp.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      )
;

--FOR LANGUAGE DATA
CREATE OR REPLACE FORCE VIEW "IFSAPP"."SCG_COPY_PART_CATALOG_LANG" ( "LANGUAGE_CODE_PCL", "DESCRIPTION_PCL") AS 
SELECT pcl.LANGUAGE_CODE, pcl.DESCRIPTION
FROM ifsapp.PART_MANUFACTURER_TAB pm, ifsapp.PART_CATALOG_TAB pc, ifsapp.PART_CATALOG_LANGUAGE_TAB pcl 
WHERE 1=1
  AND pc.PART_NO = pcl.PART_NO
  AND pc.PART_NO = pm.PART_NO
  AND pc.PART_NO = '5308509'
  AND pm.MANUFACTURER_NO = 'BR-SP'
  AND (
        to_number(to_char(pcl.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      )
;


-- aggregate all part catalog data
CREATE OR REPLACE FORCE VIEW "IFSAPP"."SCG_COPY_PART_CATALOG" (
-- PART_CATALOG_TAB columns:
    "PART_NO_PC", "DESCRIPTION", "PART_MAIN_GROUP", "INFO_TEXT", "STD_NAME_ID", "UNIT_CODE", "ROWVERSION_PC", "SERIAL_TRACKING_CODE", "ENG_SERIAL_TRACKING_CODE", "SERIAL_RULE",
    "LOT_TRACKING_CODE", "CONFIGURABLE", "CUST_WARRANTY_ID", "SUP_WARRANTY_ID", "CONDITION_CODE_USAGE", "LOT_QUANTITY_RULE", "SUB_LOT_RULE", "POSITION_PART",
    "INPUT_UNIT_MEAS_GROUP_ID", "CATCH_UNIT_CODE", "CATCH_UNIT_ENABLED", "MULTILEVEL_TRACKING", "COMPONENT_LOT_RULE", "TEXT_ID$", "STOP_ARRIVAL_ISSUED_SERIAL",
    "ALLOW_AS_NOT_CONSUMED", "WEIGHT_NET", "VOLUME_NET", "UOM_FOR_WEIGHT_NET", "UOM_FOR_VOLUME_NET", "FREIGHT_FACTOR", "RECEIPT_ISSUE_SERIAL_TRACK", "STOP_NEW_SERIAL_IN_RMA",
    "STORAGE_WIDTH_REQUIREMENT", "STORAGE_HEIGHT_REQUIREMENT", "STORAGE_DEPTH_REQUIREMENT", "UOM_FOR_LENGTH", "STORAGE_VOLUME_REQUIREMENT", "UOM_FOR_VOLUME", "STORAGE_WEIGHT_REQUIREMENT",
    "UOM_FOR_WEIGHT", "MIN_STORAGE_TEMPERATURE", "MAX_STORAGE_TEMPERATURE", "UOM_FOR_TEMPERATURE", "MIN_STORAGE_HUMIDITY", "CAPACITY_REQ_GROUP_ID", "CONDITION_REQ_GROUP_ID", "CAPABILITY_REQ_GROUP_ID", "ROWKEY_PC",
-- PART_MANUFACTURER_TAB columns
    "PART_NO_PM", "MANUFACTURER_NO_PM", "PREFERRED_MANUFACTURER", "NOTE", "DATE_CREATED_PM", "USER_CREATED_PM", "DATE_CHANGED_PM", "USER_CHANGED_PM", "ROWVERSION_PM",
-- PART_CATALOG_cft custom field columns
    "CF$_PIM_FLAG",
-- PART_MANU_PART_NO_TAB columns   
    "PART_NO_PMP", "MANUFACTURER_NO_PMP", "MANU_PART_NO", "PREFERRED_MANU_PART", "COMM_GEN_DESCRIPTION", "APPROVED_DATE", "APPROVED_USER", "APPROVED_NOTE", "MANUFACTURER_MTTR", "EXPERIENCED_MTTR",
    "MTBF_MTTR_UNIT", "CATALOG_PRICE", "CATALOG_CURRENCY", "APPROVED", "DATE_CREATED_PMP", "USER_CREATED_PMP", "DATE_CHANGED_PMP", "USER_CHANGED_PMP", "ROWVERSION_PMP", "ROWKEY_PMP",
-- PART_CATALOG_LANGUAGE_TAB columns
    "LANGUAGE_CODE_PCL", "DESCRIPTION_PCL"
    ) AS 
SELECT 
    pc.PART_NO, pc.DESCRIPTION, pc.PART_MAIN_GROUP, pc.INFO_TEXT, pc.STD_NAME_ID, pc.UNIT_CODE, pc.ROWVERSION, pc.SERIAL_TRACKING_CODE, pc.ENG_SERIAL_TRACKING_CODE, pc.SERIAL_RULE,
    pc.LOT_TRACKING_CODE, pc.CONFIGURABLE, pc.CUST_WARRANTY_ID, pc.SUP_WARRANTY_ID, pc.CONDITION_CODE_USAGE, pc.LOT_QUANTITY_RULE, pc.SUB_LOT_RULE, pc.POSITION_PART,
    pc.INPUT_UNIT_MEAS_GROUP_ID, pc.CATCH_UNIT_CODE, pc.CATCH_UNIT_ENABLED, pc.MULTILEVEL_TRACKING, pc.COMPONENT_LOT_RULE, pc.TEXT_ID$, pc.STOP_ARRIVAL_ISSUED_SERIAL,
    pc.ALLOW_AS_NOT_CONSUMED, pc.WEIGHT_NET, pc.VOLUME_NET, pc.UOM_FOR_WEIGHT_NET, pc.UOM_FOR_VOLUME_NET, pc.FREIGHT_FACTOR, pc.RECEIPT_ISSUE_SERIAL_TRACK, pc.STOP_NEW_SERIAL_IN_RMA,
    pc.STORAGE_WIDTH_REQUIREMENT, pc.STORAGE_HEIGHT_REQUIREMENT, pc.STORAGE_DEPTH_REQUIREMENT, pc.UOM_FOR_LENGTH, pc.STORAGE_VOLUME_REQUIREMENT, pc.UOM_FOR_VOLUME, pc.STORAGE_WEIGHT_REQUIREMENT,
    pc.UOM_FOR_WEIGHT, pc.MIN_STORAGE_TEMPERATURE, pc.MAX_STORAGE_TEMPERATURE, pc.UOM_FOR_TEMPERATURE, pc.MIN_STORAGE_HUMIDITY, pc.CAPACITY_REQ_GROUP_ID, pc.CONDITION_REQ_GROUP_ID, pc.CAPABILITY_REQ_GROUP_ID, pc.ROWKEY,
    pm.PART_NO, pm.MANUFACTURER_NO, pm.PREFERRED_MANUFACTURER, pm.NOTE, pm.DATE_CREATED, pm.USER_CREATED, pm.DATE_CHANGED, pm.USER_CHANGED, pm.ROWVERSION,
    pccft.CF$_PIM_FLAG,
    pmp.PART_NO, pmp.MANUFACTURER_NO, pmp.MANU_PART_NO, pmp.PREFERRED_MANU_PART, pmp.COMM_GEN_DESCRIPTION, pmp.APPROVED_DATE, pmp.APPROVED_USER, pmp.APPROVED_NOTE, pmp.MANUFACTURER_MTTR, pmp.EXPERIENCED_MTTR,
    pmp.MTBF_MTTR_UNIT, pmp.CATALOG_PRICE, pmp.CATALOG_CURRENCY, pmp.APPROVED, pmp.DATE_CREATED, pmp.USER_CREATED, pmp.DATE_CHANGED, pmp.USER_CHANGED, pmp.ROWVERSION, pmp.ROWKEY,
    pcl.LANGUAGE_CODE, pcl.DESCRIPTION
FROM ifsapp.PART_CATALOG_cft pccft, ifsapp.PART_MANUFACTURER_TAB pm, ifsapp.PART_MANU_PART_NO_TAB pmp, ifsapp.PART_CATALOG_TAB pc
      left outer join ifsapp.PART_CATALOG_LANGUAGE_TAB pcl 
        on pc.PART_NO = pcl.PART_NO
WHERE 1=1
  AND pc.ROWKEY = pccft.ROWKEY
  AND pc.PART_NO = pm.PART_NO
  AND pmp.PART_NO = pc.PART_NO
  AND pm.MANUFACTURER_NO = pmp.MANUFACTURER_NO
  AND pc.PART_NO = '5308509'
  AND pm.MANUFACTURER_NO = 'BR-SP'
  AND (
        to_number(to_char(pc.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600) -- record was changed in the last 60 mins
      OR
        to_number(to_char(pm.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      OR
        to_number(to_char(pmp.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      OR
        to_number(to_char(pcl.ROWVERSION, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
      )
;


----------------------------------------------------------------------------------------------------
--------------INVENTORY PART DATA------------------------------------------------------------
----------------------------------------------------------------------------------------------------

SELECT 
-- inventory part
  ip.part_no, ip.contract, ip.asset_class, ip.accounting_group, ip.country_of_origin, ip.HAZARD_CODE, ip.NOTE_ID, ip.PART_STATUS, ip.PLANNER_BUYER, ip.PRIME_COMMODITY, ip.PART_PRODUCT_CODE, ip.PART_PRODUCT_FAMILY,
  ip.SECOND_COMMODITY, ip.UNIT_MEAS, ip.DESCRIPTION, ip.ABC_CLASS, ip.AVAIL_ACTIVITY_STATUS, ip.COUNT_VARIANCE, ip.CREATE_DATE, ip.CYCLE_CODE, ip.CYCLE_PERIOD, ip.DIM_QUALITY, ip.CUSTOMS_STAT_NO, ip.LAST_ACTIVITY_DATE,
  ip.DURABILITY_DAY, ip.LEAD_TIME_CODE, ip.EXPECTED_LEADTIME, ip.MANUF_LEADTIME, ip.OE_ALLOC_ASSIGN_FLAG, ip.ONHAND_ANALYSIS_FLAG, ip.PURCH_LEADTIME, ip.NOTE_TEXT, ip.SUPERSEDED_BY, ip.SUPERSEDES, ip.TYPE_DESIGNATION,
  ip.ZERO_COST_FLAG, ip.SUPPLY_CODE, ip.ENG_ATTRIBUTE, ip.SHORTAGE_FLAG, ip.FORECAST_CONSUMPTION_FLAG, ip.STOCK_MANAGEMENT, ip.WEIGHT_NET, ip.INTRASTAT_CONV_FACTOR, ip.PART_COST_GROUP_ID, ip.DOP_CONNECTION, ip.STD_NAME_ID,
  ip.EAN_NO, ip.INVENTORY_VALUATION_METHOD, ip.NEGATIVE_ON_HAND, ip.TECHNICAL_COORDINATOR_ID, ip.ACTUAL_COST, ip.ACTUAL_COST_ACTIVATED, ip.MAX_ACTUAL_COST_UPDATE, ip.CUST_WARRANTY_ID, ip.SUP_WARRANTY_ID, ip.REGION_OF_ORIGIN,
  ip.INVENTORY_PART_COST_LEVEL, ip.EXT_SERVICE_COST_METHOD, ip.SUPPLY_CHAIN_PART_GROUP, ip.QTY_CALC_ROUNDING, ip.INPUT_UNIT_MEAS_GROUP_ID, ip.INVOICE_CONSIDERATION, ip.AUTOMATIC_CAPABILITY_CHECK, ip.DOP_NETTING, ip.CO_RESERVE_ONH_ANALYS_FLAG,
  ip.CATCH_UNIT_MEAS, ip.LIFECYCLE_STAGE, ip.FREQUENCY_CLASS, ip.FIRST_STAT_ISSUE_DATE, ip.LATEST_STAT_ISSUE_DATE, ip.MIN_DURAB_DAYS_CO_DELIV, ip.MIN_DURAB_DAYS_PLANNING, ip.EARLIEST_ULTD_SUPPLY_DATE, ip.PUTAWAY_ZONE_REFILL_OPTION,
  ip.STORAGE_WIDTH_REQUIREMENT, ip.STORAGE_HEIGHT_REQUIREMENT, ip.STORAGE_DEPTH_REQUIREMENT, ip.STORAGE_VOLUME_REQUIREMENT, ip.STORAGE_WEIGHT_REQUIREMENT, ip.MIN_STORAGE_TEMPERATURE, ip.MAX_STORAGE_TEMPERATURE, ip.MIN_STORAGE_HUMIDITY,
  ip.STANDARD_PUTAWAY_QTY, ip.PALLET_HANDLED
  
FROM ifsapp.INVENTORY_PART_tab ip, ifsapp.INVENTORY_PART_CHAR_tab ipc
WHERE 1=1
AND ip.PART_NO = ipc.PART_NO
AND ip.part_no = '5308509'
AND ip.contract = 'XGIN'
AND to_number(to_char(ip.rowversion, 'yyyymmddhh24miss')) > (to_number(to_char(sysdate, 'yyyymmddhh24miss')) - 3600)
;



































